### ISSUE TITLE
Add an example assembly program

### ISSUE THREAD

**Issue by mjgpy3** [douggilliland/R32V2020#1]
I added a super [silly example on the assembler branch](https://github.com/douggilliland/R32V2020/blob/assembler/Assembler/test.asm) but it might be nice to have a larger example program.

**Comment by douggilliland** [comment]
I can't find it. 

Did you see I made a Wiki? I am going to move all documents into the wiki and eliminate the documents.

**Comment by douggilliland** [comment]
Here is an example:
https://github.com/douggilliland/R32V2020/wiki/UART-loopback-Example

**Comment by mjgpy3** [comment]
@douggilliland excellent example, thank you!

**Comment by mjgpy3** [comment]
That'll give me a nice basis to work off of.
