### ISSUE TITLE
Op arguments should be comma delimited

### ISSUE THREAD

**Issue by mjgpy3** [douggilliland/R32V2020#14]
Instead of space

**Comment by mjgpy3** [comment]
@douggilliland to implement this, I basically made commas effectively whitespace. Is that too greedy?

The implications are that all of the following would be valid

```asm
adr  r10,r11,r12
adr  r10 r11 r12
adr,r10,r11,r12
adr  r10,r11,,,,  ,,,,  ,,,,,,   ,, ,,,r12
```

The last example's a little silly, but what do you think? I got the idea from Clojure programming language.

**Comment by douggilliland** [comment]
I like it. Even the last one ;)

**Comment by douggilliland** [comment]
Might make my typing mistakes less onerous ;)
