### ISSUE TITLE
Copy opcodes into CSV

### ISSUE THREAD

**Issue by mjgpy3** [douggilliland/R32V2020#16]
We need to get the correct, updated list of opcodes into the [CSV](https://github.com/douggilliland/R32V2020/blob/master/Assembler/ops.csv).

**Comment by douggilliland** [comment]
If I format the original smarter than we could do a save as CSV and get it directly.

**Comment by mjgpy3** [comment]
@douggilliland sounds good!

**Comment by douggilliland** [comment]
@mjgpy3 I loaded opcodes into:

https://github.com/douggilliland/R32V2020/blob/master/Architecture/OpCodes/OpCodes.csv

**Comment by mjgpy3** [comment]
@douggilliland I put the `form` column in the excel file and exported it as `ops.csv`.
