### ISSUE TITLE
Valid immediate value representations

### ISSUE THREAD

**Issue by mjgpy3** [douggilliland/R32V2020#3]
Decimal is easy, I assume, `42` means `42` for example.

For hex, should we use something like `0x2a`?

@douggilliland you mentioned that there would be binary as well, is there a way to encode this?

**Comment by mjgpy3** [comment]
Also, what about floating point? Do RISCs typically support those?

**Comment by douggilliland** [comment]
There are several representations of binaries that are common.

The PIC uses: b'00001111' for example. That would work well.

**Comment by mjgpy3** [comment]
@douggilliland thanks! I'll implement that shortly :)
