### ISSUE TITLE
Register aliases

### ISSUE THREAD

**Issue by mjgpy3** [douggilliland/R32V2020#5]
@douggilliland let me know what you want these to be called.

**Comment by douggilliland** [comment]
@mjgpy3 
Register Alias values
r0 AKA (Also Known As) ZERO
r1 AKA ONE
r2 AKA MINUS1
r3 AKA CCR
r4 AKA SAR
r5 AKA PAR
r6 DAR
r7 AKA PC
r8 AKA GP0
r9 AKA GP1
r10 AKA GP2
r11 AKA GP3
r12 AKA GP4
r13 AKA GP5
r14 AKA GP6
r15 AKA GP7
