### ISSUE TITLE
#define would be really helpful

### ISSUE THREAD

**Issue by douggilliland** [douggilliland/R32V2020#58]
@mjgpy3 Something like #define could be very helpful for keeping tracks of constants - like the ports in the memory map.

Would be something like the C version:

#define _SERIAL_PORT_BASE 0x1000

Then it could be used with something like:

lix r9,_SERIAL_PORT_BASE.lower

**Comment by mjgpy3** [comment]
@douggilliland would `#DEFINE` work like a standard c-style precompiler directive?

E.g. `#define SOME_A SOME_B` basically means replace every occurrence of `SOME_A` with `SOME_B` in the file? Should it span files or only work in the file containing the `#define`?

**Comment by douggilliland** [comment]
@mjgpy3 
Yep, just like C. 
Doesn't probably matter if it is local to the file or persists into the include files.

**Comment by mjgpy3** [comment]
Is it okay to require that `#define` comes before usage of the term it defines? I shouldn't need another pass if this is acceptable.

**Comment by mjgpy3** [comment]
Also, I'm going to restrict the definable terms to alphanumeric plus `_` if that's okay.

**Comment by mjgpy3** [comment]
I know C let's one do some pretty crazy stuff with these :)

**Comment by mjgpy3** [comment]
Also I'm going to make this replace at the _token_ level. In other words crazy things like the following aren't allowed.

``` asm
#DEFINE dr di
addr r10, r11, 42
```

To try to get
``` asm
addi r10, r11, 42
```
