### ISSUE TITLE
Add data locations in lst file

### ISSUE THREAD

**Issue by douggilliland** [douggilliland/R32V2020#63]
@mjgpy3 
Can you add addresses to the data values? Similar to the address column for instructions?

ex:
label1: .long 0x12345678
label2: .long 0x88776655

Would produce something like:

label1:
00000000 12345678
label2:
00000004 88776655

**Comment by mjgpy3** [comment]
@douggilliland they wouldn't increment the instruction pointer, right?

E.g.
```
label1: .long 0x42
addr r8, r9, r10
```

Would put the following?
```
00000000 label1: .long 0x42
00000000 addr r8, r9, r10
```

**Comment by douggilliland** [comment]
@mjgpy3 - yep
