### ISSUE TITLE
"Upgrade" assembler to Python 3

### ISSUE THREAD

**Issue by mjgpy3** [douggilliland/R32V2020#65]
I hate to say it but the python folks are moving on :(

https://pythonclock.org

**Comment by douggilliland** [comment]
@mjgpy3 
I upgraded to Python 3 but broke something.

Checksum should be two digits. Looks like it's now 1 digit.

start:
00000000	D4000105	bsr		clearScreen_mmXGA
; Print the title
00000001	42800000	lix		r8,0x0000			; Upper left corner of screen
``
Is making code:

```
:04000000D40001052
:04000100428000003
```
Looks like only 1 digit of checksum. Not sure what I broke in making code run under Py3.

I did replace xranges with ranges if that helps.

**Comment by mjgpy3** [comment]
@douggilliland please double check that the python 3 stuff works. All my tests passed.

**Comment by douggilliland** [comment]
@mjgpy3 Compiled and ran on the hardware!!! Thanks!!!
